exp:
  exp_name: 'radarmp_test'
  cuda_device: '0,1,2'
  mode: 'train'
  no_cuda: false
  num_workers: 16
  seed: 1234
  train_seq: ['1', '30', '21', '12', '2', '9', '31', '28']  # '1', '5', '30', '21', '42'
  val_seq: ['7', '16']  # '35', '7'
path:
  path_head: '/home/data/K-Radar/K-Radar/'
  data_path: '/home/data/K-Radar/K-Radar/generated_files/'
  axis_path: ['info_arr.mat', 'arr_doppler.mat']
  calib_path: 'info_calib/calib_radar_lidar.txt'
  label_path: 'info_label_sceneflow'
  lidar_path: 'os2-64'
  radartensor_path: 'radar_tensor'
  radartensor2d_path: 'radar_tensor2d'
  flow2dmodel_path: 'Checkpoints/radarflow2d_test4/models/flow2dmodel_89.t7'
  # model_path: 'Checkpoints/radarmp_test1/models/model_100.t7'
radar_tensor_dim:
  range: 128
  azimuth: 48
  elevation: 32
  doppler: 64
radarmp:
  dopmlp:
    output_channel: 8
  resnet3d:
    baseplane: 32
    widen_factor: 1.0
  seg:
    seg_rae64_att: 128
    seg_ae_att: 128
    output_dims: 64
    num_heads: 2
    num_layers: 2
  correlation:
    num_heads: 3
    num_levels: 3
    num_points: 50
    embed_dims: 96
    output_dims: 96
train_params:
  batch_size: 9
  decay_epochs: 3
  decay_rate: 0.9
  warmup_epochs: 5
  epochs: 100
  lr: 0.001
